version: '3'

vars:
  APP_BIN: "./bin/app{{exeExt}}"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list-all

  # Database tasks
  db:up:
    desc: Start PostgreSQL database in Docker
    cmds:
      - docker-compose up -d

  db:down:
    desc: Stop PostgreSQL database
    cmds:
      - docker-compose down

  db:logs:
    desc: Show database logs
    cmds:
      - docker-compose logs -f postgres

  # sqlc tasks
  sqlc:generate:
    desc: Generate Go code from SQL queries using sqlc in Docker
    cmds:
      - docker run --rm -v "${PWD}:/src" -w /src sqlc/sqlc:1.30.0 generate

  # Build tasks
  build:
    desc: Build main application
    cmds:
      - go build -o {{.APP_BIN}} ./cmd/app

  run:
    desc: Run the main application
    deps: [build:app]
    cmds:
      - "{{.APP_BIN}}"

  run:dev:
    desc: Run the application without building (using go run)
    cmds:
      - go run ./cmd/app

  # Code quality tasks
  fmt:
    desc: Format Go code
    cmds:
      - go fmt ./...

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  lint:
    desc: Run golangci-lint in Docker
    cmds:
      - docker run --rm -v "${PWD}:/app" -w /app golangci/golangci-lint:v2.6.0 golangci-lint run -v --timeout=10m

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin
